### ISSUE TITLE
it takes a huge of memory

### ISSUE THREAD

**Issue by draibolit** [Jarvis73/Moving-Least-Squares#11]
When I ran the code with a 2000x2000 px image and 64 moving points, it took about 20Gib of ram, which is quite a lot to implement on server.

**Comment by Jarvis73** [comment]
@draibolit The algorithm was implemented with a lot of high-dimension tensor operations, which might cause memory waste. 

I will optimize some computation steps if I have time.

**Comment by draibolit** [comment]
@Jarvis73 That could be great if you could reconstruct it. I tried to port some numpy array to dask array and was able to reduce memory usage from around 18 Gib to around more than 10 Gib although I couldn't understand very well every code line. Even that, It is still impossible to fit into ram without reduce the image size about half.

**Comment by Jarvis73** [comment]
Hi, @draibolit 
I reconstruct the code and optimize the memory usage. Now for the example of a 2000x2000px image and 64 moving points, it takes about 4GB of memory for all three algorithms.
