### ISSUE TITLE
论文写错的

### ISSUE THREAD

**Issue by XuankeShi** [Jarvis73/Moving-Least-Squares#12]
![image](https://user-images.githubusercontent.com/40144955/99189736-9babac00-279d-11eb-882e-12111df438fa.png)
这个地方的=号应该是+号吧

**Comment by Jarvis73** [comment]
@XuankeShi 论文没写错. 

首先论文要求 <a href="https://www.codecogs.com/eqnedit.php?latex=M^TM=\lambda^2I" target="_blank"><img src="https://latex.codecogs.com/gif.latex?M^TM=\lambda^2I" title="M^TM=\lambda^2I" /></a>,  这个等式的含义是 M 是一个正交阵(列向量的).  

至于 <a href="https://www.codecogs.com/eqnedit.php?latex=M_1^TM_1=\lambda^2,\;&space;M_2^TM_2=\lambda^2,\;&space;M_1^TM_2=0" target="_blank"><img src="https://latex.codecogs.com/gif.latex?M_1^TM_1=\lambda^2,\;&space;M_2^TM_2=\lambda^2,\;&space;M_1^TM_2=0" title="M_1^TM_1=\lambda^2,\; M_2^TM_2=\lambda^2,\; M_1^TM_2=0" /></a>, 这都是正交阵的定义.
