### ISSUE TITLE
Faster running time

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [Jarvis73/Moving-Least-Squares#14]
Hi, is there a way to obtain faster running times? Like optimizing some part of the code for example

**Comment by Jarvis73** [comment]
@LorenzoAgnolucci 
~~I think the algorithm can be accelerated by GPU with CUDA, but I don't have much time to look into it now.~~

A simple way is to input a smaller grid and upsample the resulting transformation to the original size. 

**Now the algorithms are implemented by PyTorch which gives a significant acceleration.** (I found it quite easy benefiting from the similar PyTorch API.) ([README](https://github.com/Jarvis73/Moving-Least-Squares#accelerating-by-pytorch))

**Comment by LorenzoAgnolucci** [comment]
@Jarvis73 Great job! Thank you very much!
