### ISSUE TITLE
Different results between Numpy and PyTorch versions

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [Jarvis73/Moving-Least-Squares#15]
Hi, I have tried to compare the results of the affine deformation of `demo()` and `demo_pytorch()` in `demo.py` using the Monalisa image with the control points given in `demo2()` and the results are not exactly equal as I expected. For some indices, the pixel values of the two images are _slightly_ different ~~(even for about 40 out of 256)~~ and I can't understand why. Do you have any idea why this happens?

**Comment by Jarvis73** [comment]
@LorenzoAgnolucci 
I think the differences come from the undetermined float operation. For example, the matrix multiplication `torch.matmul` and `numpy.matmul` may give non-identical results as discussed in pytorch/pytorch#17678.

**Comment by LorenzoAgnolucci** [comment]
Thank you very much, I didn't know there was a difference between these two operations.
