### ISSUE TITLE
The process of generating a mapping function(matrix) and applying it to image should be separated.

### ISSUE THREAD

**Issue by gwy15** [Jarvis73/Moving-Least-Squares#3]
The process of generating a mapping function(matrix) and applying it to image should be separated.

Sometimes we need to deform two or more images with the same mapping function at the same time. For example, in image augmentation which is common in semantic segmentation, one needs to deform both the original image and its pixel-wise labeled image. Under this circumstance, calling the deformation function twice with same `p` and `q` is not the best solution.
If the deformation function I choose here is a inverse function, which has a `O(n^3)` algorithm complexity as it contains a matrix inverse operation, I would have to at least double my time. But once we've separated the generation process and the final mapping process, only one `O(n^3)` operation would be needed plus two mapping operation which has `O(n^2)` complexity.

**Comment by Jarvis73** [comment]
Thanks for you contribution!

**Comment by Jarvis73** [comment]
Sorry, I don't have much time to work on this repository. And welcome pull requests for your suggestion.

**Comment by Jarvis73** [comment]
Hi, @gwy15 
After reconstructing the code, the mapping function only returns the transformation matrix, and now you can apply it on multiple images without re-computing the transformation.
