### ISSUE TITLE
Using mesh for the deformation

### ISSUE THREAD

**Issue by ghost** [Jarvis73/Moving-Least-Squares#4]
I was able to run this code on an image. Can I also using it in a 3D/2D mesh?
Meaning, If I only want to deform 1 object (that has mesh) from the image 

Thanks!
Efrat

**Comment by Jarvis73** [comment]
You can not operate single object directly. But you can add a series of extra control points surrounding the object and holding their positions, just like the example of [Monalisa](https://github.com/Jarvis73/Moving-Least-Squares/blob/master/images/monalisa_3_rigid.png).
