### ISSUE TITLE
有关逆变换

### ISSUE THREAD

**Issue by shiluooulihs** [Jarvis73/Moving-Least-Squares#7]
做基于最小二乘变形时，逆变换公式为什么不通过将dst点作为原始输入点，src点作为变形过后的点，求取变形公式？

**Comment by Jarvis73** [comment]
@shiluooulihs 可否用doc中的符号来描述问题?

**Comment by shiluooulihs** [comment]
在计算点集p到q的逆变换时，为什么不把q当做输入，p看作q经过MLS变换后的坐标，计算q到p的变换公式？

**Comment by Jarvis73** [comment]
@shiluooulihs 这样和原来的变换目的并不等价呀.

**Comment by Jarvis73** [comment]
@shiluooulihs  非常感谢你提供的思路, 我之前想的太复杂了, 实际上不需要逆变换, 只需要从目标图变换到原始图就好了. 我更新了代码.
