### ISSUE TITLE
the deformed result is different from the paper?

### ISSUE THREAD

**Issue by tengshaofeng** [Jarvis73/Moving-Least-Squares#9]

**Comment by tengshaofeng** [comment]
您好，你的工作做的很漂亮，对我来说很有参考价值。我看你的结果和原论文的不一致，是不是控制点坐标不同？ 还有你的那个逆变换的数学计算过程能否教我一下，我从正变换求逆变换求不出来

**Comment by Jarvis73** [comment]
@tengshaofeng 实际上不需要逆变换, 只需要从目标图变换到原始图就好了. 我更新了代码.
